### ISSUE TITLE
Runtime Imgui assertion error in Blender 3.5.1

### ISSUE THREAD

**Issue by ItsCubeTime** [eliemichel/BlenderImgui#3]
I see:
```
Traceback (most recent call last):   File "C:\Users\olliv\Desktop\Art And Development\Blender Shared Addons and Scripts\addons\ImguiExample\blender_imgui.py", line 314, in draw     cb(context)   File "C:\Users\olliv\Desktop\Art And Development\Blender Shared Addons and Scripts\addons\ImguiExample\overlays.py", line 45, in draw     imgui.begin("", closable=False, flags=flags)   File "imgui\core.pyx", line 4213, in imgui.core.begin imgui.core.ImGuiError: ImGui assertion error (name != NULL && name[0] != '\0') at imgui-cpp/imgui.cpp:5675
```

When I attempt to activate the Blender Imgui example addon in Blender 3.5.1, no UI from the addon will be displayed

It affects my addon FastPBR as well (which has BlenderImgui as a dependency), any help would be appreciated.

**Comment by KarryCharon** [comment]
@ItsCubeTime 
Just modify line 45 of "C:\Users\olliv\Desktop\Art And Development\Blender Shared Addons and Scripts\addons\ImguiExample\overlays.py" file, 
```python
imgui.begin("", closable=False, flags=flags)  -> imgui.begin("Some Title", closable=False, flags=flags)
```
which cased by Empty Name.

**Comment by eliemichel** [comment]
Thx for the suggested fix!
